In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5,6])

In [3]:
vector[2]

3

In [5]:
matrix = np.matrix([[1,2],
                  [3,4],
                  [5,6]])

In [6]:
matrix

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [8]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
matrix.shape

(3, 4)

In [10]:
matrix.size

12

In [12]:
matrix.ndim

2

In [13]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
np.dot(vector_a, vector_b)

32

In [14]:
matrix_a = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,2]])
matrix_b = np.array([[1,3,1],
                    [1,3,1],
                    [1,3,8]])

In [16]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [17]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [18]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [19]:
add_100 = lambda i: i+100

In [21]:
vectorized_add_100 = np.vectorize(add_100)

In [22]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [33]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [34]:
np.max(matrix)

9

In [35]:
np.min(matrix)

1

In [36]:
matrix.max()

9

In [37]:
matrix.min()

1

In [38]:
np.max(matrix, axis = 0)

array([7, 8, 9])

In [39]:
np.max(matrix, axis = 1)

array([3, 6, 9])

In [40]:
matrix.max(axis = 0)

array([7, 8, 9])

In [41]:
matrix.max(axis = 1)

array([3, 6, 9])

In [42]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [44]:
np.mean(matrix)

5.0

In [45]:
matrix.mean()

5.0

In [46]:
np.var(matrix)

6.666666666666667

In [47]:
matrix.var()

6.666666666666667

In [48]:
np.std(matrix)

2.581988897471611

In [49]:
matrix.std()

2.581988897471611

In [50]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

## Random

In [51]:
np.random.randint(0,11,3)

array([9, 1, 7])

In [52]:
np.random.randint(0,11,4)

array([1, 2, 9, 7])

In [53]:
np.random.normal(0.0, 1.0, 3)

array([-0.47620238,  0.38172243, -1.5713387 ])