In [1]:
import numpy as np

In [2]:
matrix  = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

In [3]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
#-1 means as many as needed
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [10]:
#equals to the last expression
matrix.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])