In [2]:
import pandas as pd
df = pd.read_csv('mtcars_Rev1.csv')

In [6]:
df.sample(5)

Unnamed: 0      vichle_names   mpg  cyl   disp     hp  drat     wt   qsec  \
24          24  Pontiac Firebird  19.2    8  400.0  175.0  3.08  3.845  17.05   
28          28    Ford Pantera L  15.8    8  351.0  264.0  4.22  3.170  14.50   
0            0         Mazda RX4  21.0    6  160.0  110.0  3.90  2.620  16.46   
17          17          Fiat 128  32.4    4   78.7   66.0  4.08  2.200  19.47   
26          26     Porsche 914-2  26.0    4  120.3   91.0  4.43  2.140  16.70   

    v_Shape   am  gear  carb  
24      0.0  0.0   3.0     2  
28      0.0  1.0   5.0     4  
0       0.0  1.0   4.0     4  
17      1.0  NaN   4.0     1  
26      0.0  1.0   5.0     2

## Count missing values

In [11]:
df.isna().sum()

Unnamed: 0      0
vichle_names    0
mpg             2
cyl             0
disp            0
hp              1
drat            1
wt              0
qsec            3
v_Shape         2
am              4
gear            3
carb            0
dtype: int64

Verify data shape

## Shape of the dataframe

In [13]:
df.shape

(32, 13)

## Get column Names

In [16]:
df.columns.tolist()

['Unnamed: 0',
 'vichle_names',
 'mpg',
 'cyl',
 'disp',
 'hp',
 'drat',
 'wt',
 'qsec',
 'v_Shape',
 'am',
 'gear',
 'carb']

## Count different values in column

In [18]:
df.vichle_names.value_counts()

Merc 450SLC            1
Toyota Corolla         1
Mazda RX4              1
Dodge Challenger       1
Honda Civic            1
Merc 450SE             1
Maserati Bora          1
Chrysler Imperial      1
Cadillac Fleetwood     1
Datsun 710             1
Fiat X1-9              1
Mazda RX4 Wag          1
Porsche 914-2          1
Camaro Z28             1
Ferrari Dino           1
Ford Pantera L         1
Merc 280C              1
Pontiac Firebird       1
Hornet Sportabout      1
Merc 450SL             1
Merc 230               1
Lincoln Continental    1
Hornet 4 Drive         1
AMC Javelin            1
Duster 360             1
Toyota Corona          1
Volvo 142E             1
Valiant                1
Lotus Europa           1
Merc 280               1
Fiat 128               1
Merc 240D              1
Name: vichle_names, dtype: int64

In [19]:
df['vichle_names'].value_counts()

Merc 450SLC            1
Toyota Corolla         1
Mazda RX4              1
Dodge Challenger       1
Honda Civic            1
Merc 450SE             1
Maserati Bora          1
Chrysler Imperial      1
Cadillac Fleetwood     1
Datsun 710             1
Fiat X1-9              1
Mazda RX4 Wag          1
Porsche 914-2          1
Camaro Z28             1
Ferrari Dino           1
Ford Pantera L         1
Merc 280C              1
Pontiac Firebird       1
Hornet Sportabout      1
Merc 450SL             1
Merc 230               1
Lincoln Continental    1
Hornet 4 Drive         1
AMC Javelin            1
Duster 360             1
Toyota Corona          1
Volvo 142E             1
Valiant                1
Lotus Europa           1
Merc 280               1
Fiat 128               1
Merc 240D              1
Name: vichle_names, dtype: int64

In [31]:
df.to_json('mtcars_Rev1.json')

In [29]:
json_df = pd.read_json('mtcars_Rev1.json')

In [30]:
json_df

,vichle_names,mpg,cyl,disp,hp,drat,wt,qsec,v_Shape,am,gear,carb
0   0,Mazda RX4,21.0,6,160.0,110.0,3.9,2.62,16.46,...             
1   1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.9,2.875,1...             
10  10,Merc 280C,,6,167.6,123.0,3.92,3.44,18.9,1.0...             
11  11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.07,17....             
12  12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.73,,0....             
13  13,Merc 450SLC,15.2,8,275.8,180.0,3.07,3.78,18...             
14  14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,...             
15  15,Lincoln Continental,10.4,8,460.0,215.0,3.0,...             
16  16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5...             
17  17,Fiat 128,32.4,4,78.7,66.0,4.08,2.2,19.47,1....             
18  18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18....             
19  19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,...             
2   2,Datsun 710,,4,108.0,93.0,3.85,2.32,18.61,1.0...             
20  20,Toyota Corona,21.5,4,120.1,97.0,3.7,2.465,2...             
21  21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3....             
22  22,AMC Javelin,15.2,8,304.0,150.0,3.15,3.435,1...             
23  23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.84,15....             
24  24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3....             
25  25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.9,...             
26  26,Porsche 914-2,26.0,4,120.3,91.0,4.43,2.14,1...             
27  27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.51300...             
28  28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.17...             
29  29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.77,1...             
3   3,Hornet 4 Drive,21.4,6,258.0,,3.08,3.215,19.4...             
30  30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.57,...             
31  31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.78,18....             
4   4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3....             
5   5,Valiant,18.1,6,225.0,105.0,2.76,3.46,,1.0,0....             
6   6,Duster 360,14.3,8,360.0,245.0,,3.57,15.84,0....             
7   7,Merc 240D,24.4,4,146.7,62.0,3.69,3.19,20.0,,...             
8   8,Merc 230,22.8,4,140.8,95.0,3.92,3.15,,1.0,0....             
9   9,Merc 280,19.2,6,167.6,123.0,3.92,3.44,18.3,1...

# Generate Random Data (Regression)

In [32]:
import numpy as np

In [38]:
from sklearn.datasets import make_regression
features, target, coefficients = make_regression(n_samples = 100, 
                                                 n_features = 3, 
                                                 n_informative = 3, 
                                                 n_targets = 1, 
                                                 noise = 0.0, 
                                                 coef = True,
                                                 random_state = 1)

In [41]:
# Features matrix
features[:3]

array([[ 1.29322588, -0.61736206, -0.11044703],
       [-2.793085  ,  0.36633201,  1.93752881],
       [ 0.80186103, -0.18656977,  0.0465673 ]])

In [42]:
# Target vector
target[:3]

array([-10.37865986,  25.5124503 ,  19.67705609])

In [43]:
coefficients

array([44.19042807, 98.97517077, 58.15774073])

# Generate Random Data (Classification)

In [44]:
from sklearn.datasets import make_classification
features, target = make_classification(n_samples = 100,
                                       n_features = 3, 
                                       n_informative = 3, 
                                       n_redundant = 0, 
                                       n_classes = 2,
                                       weights = [.25, .75],
                                       random_state = 1)

In [45]:
# Features matrix
features[:3]

array([[ 1.06354768, -1.42632219,  1.02163151],
       [ 0.23156977,  1.49535261,  0.33251578],
       [ 0.15972951,  0.83533515, -0.40869554]])

In [46]:
# Target vector
target[:3]

array([1, 0, 0])